project:
  type: website
  resources:
    - robots.txt

website:
  title: sheg.cc
  site-url: https://sheg.cc/
  repo-url: https://github.com/vsheg/website
  repo-actions: [edit, issue]
  google-analytics: G-LZBXW9YKWW
  description: "sheg"
  page-navigation: true
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - text: Posts
        href: posts/
      - text: Teaching
        href: teaching/
      - text: Contact
        href: contact/
    tools:
      - icon: rss
        href: feed.xml

  search:
    location: navbar
    type: textbox
  page-footer:
    center: |
      [🦧](https://duckduckgo.com/?q=orangutan&iax=images&ia=images){.secret-link target="_blank"}

crossref:
  eq-prefix: "" # TODO: add parentheses around equation numbers
  sec-prefix: "§"
  fig-prefix: "⬟"
  tbl-prefix: "⊞"

format:
  html:
    theme:
      light: cosmo
    mermaid:
      theme: neutral
    grid:
      body-width: 1000px
      margin-width: 300px
    code-copy: hover
    code-annotations: hover
    html-math-method: mathjax

filters:
  - auto-dark

css: style.css

reference-location: margin
citation-location: margin
callout-appearance: minimal

lightbox: true

csl: https://www.zotero.org/styles/gost-r-7-0-5-2008-numeric
