project:
  type: website

website:
  title: sheg.cc
  site-url: https://sheg.cc/
  google-analytics: G-LZBXW9YKWW
  description: "sheg"
  navbar:
    left:
      - text: Posts
        href: posts/
      - text: Teaching
        href: teaching/
      - text: Contact
        href: contact/

    right:
      - icon: rss
        href: feed.xml

crossref:
  eq-prefix: "" # TODO: add parentheses around equation numbers
  sec-prefix: "§"
  fig-prefix: "⬟"
  tbl-prefix: "⊞"

format:
  html:
    theme: cosmo
    code-copy: hover
    code-annotations: hover
    html-math-method: mathjax

reference-location: margin
citation-location: margin
callout-appearance: minimal
