project:
  type: website

website:
  title: sheg.cc
  site-url: https://sheg.cc
  navbar:
    left:
      - text: About
        href: about/
      - text: Intermediate ML
        href: intermediate-ml/

    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo

reference-location: margin
citation-location: margin
callout-appearance: minimal
