project:
  type: website

website:
  title: sheg.cc
  site-url: https://sheg.cc
  description: "sheg"
  navbar:
    left:
      - text: Posts
        href: posts/
      - text: Teaching
        href: teaching/
      - text: About
        href: about/

    right:
      - icon: rss
        href: posts/index.xml

format:
  html:
    theme: cosmo
    code-copy: true
    code-annotations: hover

reference-location: margin
citation-location: margin
callout-appearance: minimal
