project:
  type: website
  resources:
    - robots.txt

website:
  title: sheg.cc
  site-url: https://sheg.cc/
  google-analytics: G-LZBXW9YKWW
  description: "sheg"
  navbar:
    left:
      - text: Posts
        href: posts/
      - icon: rss
        href: feed.xml
      - text: Teaching
        href: teaching/
      - text: Contact
        href: contact/
  search:
    location: navbar
    type: textbox
  page-footer: '[🦧](https://duckduckgo.com/?q=orangutan&iax=images&ia=images){.secret-link target="_blank"}'

crossref:
  eq-prefix: "" # TODO: add parentheses around equation numbers
  sec-prefix: "§"
  fig-prefix: "⬟"
  tbl-prefix: "⊞"

format:
  html:
    theme:
      light: cosmo
    mermaid:
      theme: neutral
    grid:
      body-width: 1000px
      margin-width: 300px
    code-copy: hover
    code-annotations: hover
    html-math-method: mathjax

filters:
  - auto-dark

css: style.css

reference-location: margin
citation-location: margin
callout-appearance: minimal

lightbox: true
