name: Development Deployment

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

concurrency: 
  group: dev
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: self-hosted
    environment: dev
    steps:
        - uses: actions/checkout@v2
        - name: Build and Up
          run: docker-compose up --build -d
