on:
  workflow_dispatch:
  push:
    branches: main

name: render

jobs:
  
  render:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y fd-find && cp $(which fdfind) /usr/local/bin/fd
      - run: sudo apt install -y pandoc
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: make
      - run: quarto render
      - run: make rss
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _site/
  
  deploy:
    needs: render
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
