name: Development Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: self-hosted
    environment: main
    env:
      WEB_PORT: ${{ secrets.WEB_PORT }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Up
        run: docker-compose up --build -d
